# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Jun Yi/Desktop/project_FDP_final/project_FDP_final.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Jun Yi/Desktop/project_FDP_final/project_FDP_final.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/Jun Yi/Desktop/project_FDP_final/project_FDP_final.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files {{C:/Users/Jun Yi/Desktop/project_FDP_final/project_FDP_final.srcs/sources_1/imports/res/weights.coe}}
add_files {{C:/Users/Jun Yi/Desktop/project_FDP_final/project_FDP_final.srcs/sources_1/imports/res/00.coe}}
read_verilog -library xil_defaultlib {
  {C:/Users/Jun Yi/Desktop/project_FDP_final/project_FDP_final.srcs/sources_1/imports/Desktop/Oled_Display.v}
  {C:/Users/Jun Yi/Desktop/project_FDP_final/project_FDP_final.srcs/sources_1/new/char_rom.v}
  {C:/Users/Jun Yi/Desktop/project_FDP_final/project_FDP_final.srcs/sources_1/new/colour_mux.v}
  {C:/Users/Jun Yi/Desktop/project_FDP_final/project_FDP_final.srcs/sources_1/new/cut_the_wire_game.v}
  {C:/Users/Jun Yi/Desktop/project_FDP_final/project_FDP_final.srcs/sources_1/new/debouncer.v}
  {C:/Users/Jun Yi/Desktop/project_FDP_final/project_FDP_final.srcs/sources_1/new/diffused_screen.v}
  {C:/Users/Jun Yi/Desktop/project_FDP_final/project_FDP_final.srcs/sources_1/new/exploded_screen.v}
  {C:/Users/Jun Yi/Desktop/project_FDP_final/project_FDP_final.srcs/sources_1/new/frame_data.v}
  {C:/Users/Jun Yi/Desktop/project_FDP_final/project_FDP_final.srcs/sources_1/new/game_2.v}
  {C:/Users/Jun Yi/Desktop/project_FDP_final/project_FDP_final.srcs/sources_1/new/game_4.v}
  {C:/Users/Jun Yi/Desktop/project_FDP_final/project_FDP_final.srcs/sources_1/new/game_4_graphics.v}
  {C:/Users/Jun Yi/Desktop/project_FDP_final/project_FDP_final.srcs/sources_1/new/game_4_logic.v}
  {C:/Users/Jun Yi/Desktop/project_FDP_final/project_FDP_final.srcs/sources_1/new/manual.v}
  {C:/Users/Jun Yi/Desktop/project_FDP_final/project_FDP_final.srcs/sources_1/new/maze_game.v}
  {C:/Users/Jun Yi/Desktop/project_FDP_final/project_FDP_final.srcs/sources_1/new/reset_instruction_screen.v}
  {C:/Users/Jun Yi/Desktop/project_FDP_final/project_FDP_final.srcs/sources_1/new/simon_say.v}
  {C:/Users/Jun Yi/Desktop/project_FDP_final/project_FDP_final.srcs/sources_1/new/start_instructions_screen.v}
  {C:/Users/Jun Yi/Desktop/project_FDP_final/project_FDP_final.srcs/sources_1/new/start_screen.v}
  {C:/Users/Jun Yi/Desktop/project_FDP_final/project_FDP_final.srcs/sources_1/new/symbol_renderer_A.v}
  {C:/Users/Jun Yi/Desktop/project_FDP_final/project_FDP_final.srcs/sources_1/new/symbol_renderer_B.v}
  {C:/Users/Jun Yi/Desktop/project_FDP_final/project_FDP_final.srcs/sources_1/new/text_engine_h.v}
  {C:/Users/Jun Yi/Desktop/project_FDP_final/project_FDP_final.srcs/sources_1/new/text_engine_v.v}
  {C:/Users/Jun Yi/Desktop/project_FDP_final/project_FDP_final.srcs/sources_1/new/tone_generator.v}
  {C:/Users/Jun Yi/Desktop/project_FDP_final/project_FDP_final.srcs/sources_1/new/top_timer.v}
  {C:/Users/Jun Yi/Desktop/project_FDP_final/project_FDP_final.srcs/sources_1/new/Top_Student.v}
}
read_vhdl -library xil_defaultlib {
  {C:/Users/Jun Yi/Desktop/project_FDP_final/project_FDP_final.srcs/sources_1/imports/Desktop/Mouse_Control.vhd}
  {C:/Users/Jun Yi/Desktop/project_FDP_final/project_FDP_final.srcs/sources_1/imports/Desktop/Ps2Interface.vhd}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Jun Yi/Desktop/project_FDP_final/project_FDP_final.srcs/constrs_1/imports/EE2026/Basys3_Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Jun Yi/Desktop/project_FDP_final/project_FDP_final.srcs/constrs_1/imports/EE2026/Basys3_Master.xdc}}]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top Top_Student -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Top_Student.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Top_Student_utilization_synth.rpt -pb Top_Student_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
